version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "04:00"
      timezone: "Europe/Zurich"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "04:00"
      timezone: "Europe/Zurich"
    # Temporarily disable version updates for npm dependencies until plugin is in active development again
    open-pull-requests-limit: 0
